apiVersion: v1
kind: Pod
metadata:
  name: HelloNginx
  labels:
    app: nginx_web_server
spec:
  containers:
  - name: FirstNginxContainer
    image: nginx:latest
    ports:
      - containerPort: 80