apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-sample
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: samplecron
              image: thorstenhans/cronjob-sample:latest
              env:
              - name: CronJobOutputFolder
                value: "/var/cron-logs"
              volumeMounts:
                - mountPath: "/var/cron-logs"
                  name: volume
          restartPolicy: OnFailure
          volumes:
            - name: volume
              persistentVolumeClaim:
                claimName: azure-fileshare
