apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefiles
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  azureFile:
    secretName: azure-secret
    shareName: aks-cron
    readOnly: false
  claimRef:
    namespace: default
    name: azure-fileshare
